// GameFormat — the sortie figure, rendered exactly as the leaderboard renders it.
//
// ===========================================================================
// THIS IS A SECOND IMPLEMENTATION, AND IT IS GRADED AGAINST THE FIRST.
//
// The device cannot ask the server to format a string on every frame, so the
// arithmetic exists twice. That is the situation rail 3 warns about, and the
// answer is not to pretend otherwise — it is that the second implementation is
// tested against output the FIRST one produced.
//
// test/fixtures/game_config_fixture.h is generated by valar-eam-feed's
// scripts/emit-device-fixture.ts, which calls the server's own
// `formatSortieDeviation` for every row. Nothing in that table was typed by
// anyone reading the server, which is the difference between a check and a
// private replica of the rule.
//
// WHAT IS NOT HERE, AND MUST NOT ARRIVE: the deviation curve. No bucketS
// literal, no metresPerBucket, no shackFloorM, no maxMissM, no clockFloorMs.
// The bucket width is a PARAMETER, served at runtime. Miss distance and SHACK
// are the server's answers and the device never computes them — they are not
// even in the generated header, only in the .json archive beside it.
//
// PURE. Only <stdint.h> and <stddef.h>; no Arduino, no snprintf, no float. The
// integer-to-text is written out by hand for that reason and not by preference.
// ===========================================================================

#ifndef BLIPSCOPE_GAME_GAMEFORMAT_H
#define BLIPSCOPE_GAME_GAMEFORMAT_H

#include <stddef.h>
#include <stdint.h>

namespace game {

/// Longest string FormatDeviation can produce, plus the terminator.
constexpr size_t kDeviationTextMax = 32;

/// Which side of T the key turn landed on. The FIGURE is a magnitude — the
/// server renders one, and the two must agree character for character — so the
/// direction is carried separately rather than as a sign on the number.
///
/// Losing early-vs-late would be losing real information the player earned;
/// putting it INSIDE the number would be disagreeing with the leaderboard about
/// what the sortie scored. It is a word next to the figure, so both survive.
enum class Sense : uint8_t {
  Exact = 0,
  Early,
  Late,
};

Sense DeviationSense(int64_t deviation_us);

/// Decimal places implied by a bucket width, derived the way the server derives
/// them — from the bucket itself, never a hardcoded `toFixed(1)`.
///
/// The server does it with `String(bucketS)` and counts the characters after
/// the point; this does it with integer arithmetic on microseconds, because a
/// draw path has no business doing floating-point. Same answer, and the fixture
/// pins three bucket widths so "same answer" is a measured claim rather than an
/// argument. Zero for an unknown (0) bucket.
uint8_t BucketDecimals(uint32_t bucket_us);

/// Render |deviation| in the server's display unit: buckets, rounded UP.
///
/// Rounded up because the bucket is a floor on what the clock can resolve, so
/// rounding down would report a precision the measurement does not have. §13
/// A.3, one layer out.
///
/// Returns false — and writes an empty string — when `bucket_us` is 0, which is
/// what an unserved config looks like. THERE IS NO DEFAULT BUCKET HERE ON
/// PURPOSE. The 2-second window has one because §12 publishes it as part of the
/// fiction; the bucket is an operational knob with a `GAME_SCORE_BUCKET_S`
/// override, so a baked default would be a second copy that drifts the first
/// time it is tuned, and it would drift SILENTLY into a plausible number.
///
/// A caller with no bucket has not got a number to show yet, and saying so is
/// the honest screen.
bool FormatDeviation(int64_t deviation_us, uint32_t bucket_us, char* out, size_t n);

}  // namespace game

#endif  // BLIPSCOPE_GAME_GAMEFORMAT_H
