// Host tests for Derive — the device port of the server's class/T derivation.
//
// ===========================================================================
// EVERY EXPECTED DERIVATION IN HERE CAME FROM THE SERVER.
//
// test/fixtures/derivation_fixture.h is generated by valar-eam-feed's
// scripts/emit-derivation-fixture.ts, which calls src/game/derive.ts -- the
// function POST /votes re-derives with and refuses a mismatch against. The
// grading is WHOLE-VALUE EQUALITY on every draw, class, tier, offset and T.
// Never loosen a comparison to make this pass: a port that is "close" is a
// device whose every vote is refused.
//
// The SHA-256 known-answer vectors are FIPS 180-4's own, plus padding-boundary
// lengths computed by an independent implementation (Node's crypto). They run
// first, so a fixture failure cannot be a hash bug in disguise.
// ===========================================================================

#include "../../src/game/Derive.h"

#include "derivation_fixture.h"  // -I test/fixtures, and only for this binary

#include <cstdio>
#include <cstring>

using namespace game;

static int g_failures = 0;
static int g_checks = 0;
static const char* g_case = "";

#define CHECK(cond, msg)                                                        \
  do {                                                                          \
    g_checks += 1;                                                              \
    if (!(cond)) {                                                              \
      g_failures += 1;                                                          \
      std::printf("  FAIL %s\n       %s\n       at %s:%d\n", g_case, msg,       \
                  __FILE__, __LINE__);                                          \
    }                                                                           \
  } while (0)

#define CASE(name)                                                              \
  g_case = name;                                                                \
  std::printf("  ---- %s\n", name);

static void Hex(const uint8_t* d, char out[65]) {
  static const char* k = "0123456789abcdef";
  for (int i = 0; i < 32; i++) {
    out[2 * i] = k[d[i] >> 4];
    out[2 * i + 1] = k[d[i] & 15];
  }
  out[64] = '\0';
}

static bool ShaIs(const char* msg, size_t len, const char* hex) {
  uint8_t d[32];
  char h[65];
  Sha256(reinterpret_cast<const uint8_t*>(msg), len, d);
  Hex(d, h);
  return std::strcmp(h, hex) == 0;
}

static void Sha256KnownAnswers() {
  CASE("SHA-256 matches FIPS 180-4 and independent boundary vectors");
  CHECK(ShaIs("", 0, "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"), "empty");
  CHECK(ShaIs("abc", 3, "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad"), "abc");
  const char* two = "abcdbcdecdefdefgefghfghighijhijkijkljklmklmnlmnomnopnopq";
  CHECK(ShaIs(two, std::strlen(two), "248d6a61d20638b8e5c026930c3e6039a33ce45964ff2167f6ecedd419db06c1"), "448-bit");
  static char a[128];
  std::memset(a, 'a', sizeof(a));
  struct { size_t n; const char* hex; } kBoundary[] = {
      {55, "9f4390f8d30c2dd92ec9f095b65e2b9ae9b0a925a5258e241c9f1e910f734318"},
      {56, "b35439a4ac6f0948b6d6f9e3c6af0f5f590ce20f1bde7090ef7970686ec6738a"},
      {63, "7d3e74a05d7db15bce4ad9ec0658ea98e3f06eeecf16b4c6fff2da457ddc2f34"},
      {64, "ffe054fe7ae0cb6dc65c3af9b61d5209f439851db43d0ba5997337df154668eb"},
      {65, "635361c48bb9eab14198e76ea8ab7f1a41685d6ad62aa9146d301d4f17eb0ae0"},
      {119, "31eba51c313a5c08226adf18d4a359cfdfd8d2e816b13f4af952f7ea6584dcfb"},
      {120, "2f3d335432c70b580af0e8e1b3674a7c020d683aa5f73aaaedfdc55af904c21c"},
  };
  for (const auto& b : kBoundary) CHECK(ShaIs(a, b.n, b.hex), "padding boundary length");
}

static DeriveParams FixtureParams() {
  DeriveParams p;
  p.epoch = derivation_fixture::kEpoch;
  for (const auto& w : derivation_fixture::kWeights) {
    p.weights[p.n_weights++] = {static_cast<MsgClass>(static_cast<uint8_t>(w.cls)), w.ppm};
  }
  for (const auto& t : derivation_fixture::kTiers) {
    // Fixture Tier has kNone at 0, like ours; the numbering is asserted below.
    p.tiers[p.n_tiers++] = {static_cast<Tier>(static_cast<uint8_t>(t.tier)), t.ppm, t.min_s, t.max_s};
  }
  return p;
}

static void EnumsLineUp() {
  CASE("the fixture's enum numbering is ours");
  CHECK(static_cast<uint8_t>(derivation_fixture::Class::kNam) == static_cast<uint8_t>(MsgClass::Nam), "nam");
  CHECK(static_cast<uint8_t>(derivation_fixture::Class::kFdm) == static_cast<uint8_t>(MsgClass::Fdm), "fdm");
  CHECK(static_cast<uint8_t>(derivation_fixture::Class::kExecution) == static_cast<uint8_t>(MsgClass::Execution), "execution");
  CHECK(static_cast<uint8_t>(derivation_fixture::Tier::kNone) == static_cast<uint8_t>(Tier::None), "none");
  CHECK(static_cast<uint8_t>(derivation_fixture::Tier::kNormal) == static_cast<uint8_t>(Tier::Normal), "normal");
  CHECK(static_cast<uint8_t>(derivation_fixture::Tier::kSnap) == static_cast<uint8_t>(Tier::Snap), "snap");
}

/// THE AGREEMENT TEST. Every case, every field, whole-value equality.
static void AgreesWithTheServer() {
  CASE("device and server derive every fixture case identically");
  const DeriveParams p = FixtureParams();
  CHECK(ParamsSound(p), "the served parameters are sound");
  CHECK(derivation_fixture::kCaseCount >= 14, "the fixture carries its coverage cases");
  for (size_t i = 0; i < derivation_fixture::kCaseCount; i++) {
    const derivation_fixture::Case& c = derivation_fixture::kCases[i];
    g_case = c.name;
    const Derivation d = Derive(c.msg_id, std::strlen(c.msg_id), c.heard_at, p);
    CHECK(d.status == DeriveStatus::Ok, "status Ok");
    CHECK(d.class_u32 == c.class_u32, "class_u32");
    CHECK(d.tier_u32 == c.tier_u32, "tier_u32");
    CHECK(d.offset_u32 == c.offset_u32, "offset_u32");
    CHECK(d.class_ppm == c.class_ppm, "class_ppm");
    CHECK(d.tier_ppm == c.tier_ppm, "tier_ppm");
    CHECK(static_cast<uint8_t>(d.cls) == static_cast<uint8_t>(c.cls), "class");
    CHECK(static_cast<uint8_t>(d.tier) == static_cast<uint8_t>(c.tier), "tier");
    CHECK(d.offset_s == c.offset_s, "offset_s");
    CHECK(d.t_at_ms == c.t_at_ms, "t_at_ms");
    if (d.t_at_ms >= 0) {
      char iso[32];
      CHECK(FormatIsoUtcMs(d.t_at_ms, iso, sizeof(iso)) == 24, "ISO length");
      CHECK(std::strcmp(iso, c.t_at) == 0, "t_at renders exactly as the server renders it");
    }
  }
}

static void IsoParsing() {
  CASE("heard_at parsing accepts what the feed serves and refuses the rest");
  int64_t ms = 0;
  CHECK(ParseIsoUtcMs("1970-01-01T00:00:00.000Z", &ms) && ms == 0, "epoch");
  CHECK(ParseIsoUtcMs("2026-09-22T14:07:55.500Z", &ms) && ms == 1790086075500LL, "milliseconds");
  CHECK(ParseIsoUtcMs("2026-09-22T14:07:55Z", &ms) && ms == 1790086075000LL, "no fraction");
  CHECK(ParseIsoUtcMs("2026-09-22T14:07:55.5Z", &ms) && ms == 1790086075500LL, "one fractional digit is tenths");
  CHECK(ParseIsoUtcMs("2028-02-29T23:59:59.999Z", &ms), "leap day");
  CHECK(!ParseIsoUtcMs("2026-02-29T00:00:00.000Z", &ms), "not a leap year");
  CHECK(!ParseIsoUtcMs("2026-09-22T14:07:55.000+00:00", &ms), "offset form is refused, not guessed");
  CHECK(!ParseIsoUtcMs("2026-09-22 14:07:55.000Z", &ms), "space separator");
  CHECK(!ParseIsoUtcMs("2026-09-22T14:07:55.1234Z", &ms), "sub-millisecond digits");
  CHECK(!ParseIsoUtcMs("2026-09-22T14:07:55.000Zjunk", &ms), "trailing bytes");
  CHECK(!ParseIsoUtcMs("2026-09-22T24:00:00.000Z", &ms), "hour 24");
  CHECK(!ParseIsoUtcMs("", &ms), "empty");
  CHECK(!ParseIsoUtcMs(nullptr, &ms), "null");
  char iso[32];
  FormatIsoUtcMs(1790086075500LL, iso, sizeof(iso));
  CHECK(std::strcmp(iso, "2026-09-22T14:07:55.500Z") == 0, "format round-trips");
  CHECK(FormatIsoUtcMs(0, iso, 24) == 0, "refuses a short buffer");
}

static void RefusesRatherThanGuesses() {
  CASE("unsound parameters and an unparseable heard_at are refused");
  const DeriveParams good = FixtureParams();
  const derivation_fixture::Case& exec = derivation_fixture::kCases[2];
  CHECK(exec.cls == derivation_fixture::Class::kExecution, "case 2 is the execution case");

  DeriveParams p = good;
  p.weights[0].ppm -= 1;  // sums to 999999
  CHECK(!ParamsSound(p), "decode sum one short");
  CHECK(Derive(exec.msg_id, std::strlen(exec.msg_id), exec.heard_at, p).status == DeriveStatus::BadParams,
        "no normalisation: a short sum is refused");

  p = good;
  p.tiers[1].ppm += 1;
  CHECK(!ParamsSound(p), "tier sum one over");

  p = good;
  p.tiers[0].max_s = p.tiers[0].min_s;
  CHECK(!ParamsSound(p), "maxS == minS");

  p = DeriveParams();
  CHECK(!ParamsSound(p), "nothing served yet");

  const Derivation bad = Derive(exec.msg_id, std::strlen(exec.msg_id), "yesterday-ish", good);
  CHECK(bad.status == DeriveStatus::BadHeardAt && bad.t_at_ms == -1, "no T from an unparseable heard_at");

  const derivation_fixture::Case& nam = derivation_fixture::kCases[0];
  const Derivation n = Derive(nam.msg_id, std::strlen(nam.msg_id), "yesterday-ish", good);
  CHECK(n.status == DeriveStatus::Ok && n.cls == MsgClass::Nam, "a NAM needs no heard_at: T is for execution only");
}

int main() {
  std::printf("Derive (device/server agreement)\n");
  Sha256KnownAnswers();
  EnumsLineUp();
  AgreesWithTheServer();
  IsoParsing();
  RefusesRatherThanGuesses();
  std::printf("  %d checks, %d failed\n", g_checks, g_failures);
  return g_failures == 0 ? 0 : 1;
}
