// GENERATED by scripts/embed-fake-ids.mjs from scripts/device-id-allowlist.txt.
// Do not edit by hand; run `node scripts/embed-fake-ids.mjs`. CI runs --check.
export const FAKE_DEVICE_IDS: ReadonlySet<string> = new Set([
  "0000000000000000",
  "0123456789abcdef",
  "beefbeefbeefbeef",
  "a1b2c3d4e5f6a7b8",
  "a1b2c3d4e5f60718",
  "b2c3d4e5f6a7b8c9",
  "dead0000beef1111",
  "1111222233334444",
  "aaaabbbbccccdddd",
  "ffffffffffffffff",
]);
