// The coastline data, owned by exactly one translation unit.
//
// It used to be #included straight into FlightAnimation.cpp inside an anonymous
// namespace, which is why nothing else could reach it (see GlobeProjection.h).
// Moving the include here changes nothing about the data -- Coastlines.inc is
// generated by scripts/gen_coastlines.py and is not touched -- and gives both
// the animation and Follow one array to share instead of one each.
//
// The .inc names bare `GeoVec` and `Coastline`, so it is included INSIDE
// namespace globeproj where those resolve to the shared definitions. No aliases,
// no edits to the generated file.
//
// A build that never calls Coastlines() drops the whole ~7.6 KB under
// --gc-sections; §7.2 measured the unreferenced cost of the module at 568 B.

#include "../../include/GlobeProjection.h"

namespace globeproj {
namespace {
#include "Coastlines.inc"
}  // namespace

const Coastline* Coastlines() { return kCoast; }
int CoastlineCount() { return (int)(sizeof(kCoast) / sizeof(kCoast[0])); }

}  // namespace globeproj
