// The coastline data, owned by exactly one translation unit.
//
// It used to be #included straight into FlightAnimation.cpp inside an anonymous
// namespace, which is why nothing else could reach it (see GlobeProjection.h).
// Moving the include here changes nothing about the data -- Coastlines.inc is
// generated by scripts/gen_coastlines.py and is not touched -- and gives both
// the animation and Follow one array to share instead of one each.
//
// The .inc names bare `GeoVec` and `Coastline`, so it is included INSIDE
// namespace globeproj where those resolve to the shared definitions. No aliases,
// no edits to the generated file.
//
// A build that never calls Coastlines() drops the whole ~7.6 KB under
// --gc-sections; §7.2 measured the unreferenced cost of the module at 568 B.

#include "../../include/GlobeProjection.h"

namespace globeproj {

// TWO SETS, SELECTED BY ZOOM (#274 step 5). Each .inc declares the same symbol
// names, so each gets its own namespace rather than an edit to a generated file.
//
// WHY BOTH ARE SHIPPED. The dense set is 10.3x the vertices and buys nothing at
// whole-earth zoom, where the extra detail is sub-pixel: measured on COM4 it
// cost 22.5 -> 41.9 ms and pushed the frame residual to +9.0 ms against a 10 ms
// gate margin. It is worth its 71 KB only once the view is zoomed in far enough
// that the coarse set would show straight edges -- 0.52 deg is 1 px at R=110 and
// 12 px at R=1349.
namespace coarse {
#include "Coastlines.inc"
}  // namespace coarse
namespace dense {
#include "CoastlinesDense.inc"
}  // namespace dense

const Coastline* Coastlines() { return coarse::kCoast; }
int CoastlineCount() { return (int)(sizeof(coarse::kCoast) / sizeof(coarse::kCoast[0])); }

const Coastline* CoastlinesDense() { return dense::kCoast; }
int CoastlineDenseCount() { return (int)(sizeof(dense::kCoast) / sizeof(dense::kCoast[0])); }

}  // namespace globeproj
