// GENERATED by scripts/embed-device-salt.mjs from include/DeviceIdentity.h.
// Do not edit by hand; run `node scripts/embed-device-salt.mjs`. CI runs --check.
export const LEADERBOARD_SALT = "blipscope-lb-v1";
