#!/usr/bin/env bash
#
# Blipscope egress relay -- idempotent root setup for one box (Debian/Ubuntu).
# Safe to re-run; converges the box to the desired state each time.
#
# WHAT IT DOES
#   - installs nginx (apt) + unattended-upgrades
#   - writes the caching relay vhost: proxy_cache + cache_lock, use_stale on
#     error/timeout/429, TTL a clearly-marked tunable (CACHE_TTL, starts 6s)
#   - X-Relay-Key gate: 403 unless the caller presents the key, read from a
#     ROOT-ONLY file (never in this script or in git)
#   - installs the Cloudflare Origin certificate for TLS (443)
#   - ufw: allow 22 + 443-from-Cloudflare-ranges only, deny the rest
#   - unauthenticated /healthz
#   - adds X-Relay-Cache: HIT|MISS|STALE|UPDATING and logs upstream_status so the
#     soak can read adsb.lol's REAL per-IP 429 behaviour from the relay's own logs
#
# PREREQUISITES -- scp these to the box first (see relay/README.md):
#   /etc/ssl/cloudflare/origin.pem   Cloudflare Origin cert   (0644 root:root)
#   /etc/ssl/cloudflare/origin.key   its private key          (0600 root:root)
#   /etc/nginx/relay.key             the X-Relay-Key value     (0600 root:root)
#
# RUN:  sudo CACHE_TTL=6s bash setup-relay.sh
set -euo pipefail

# ---- tunables ---------------------------------------------------------------
# THE scaling knob. adsb.lol request rate ~= (distinct hot tiles) / CACHE_TTL,
# independent of device count. 6s keeps a desk radar current (the device
# dead-reckons between polls) while collapsing the fleet to a trickle. Raise it
# if the soak shows adsb.lol throttling one IP at our volume; lower for freshness.
CACHE_TTL="${CACHE_TTL:-6s}"

UPSTREAM_HOST="api.adsb.lol"
CERT="/etc/ssl/cloudflare/origin.pem"
KEY="/etc/ssl/cloudflare/origin.key"
RELAY_KEY_FILE="/etc/nginx/relay.key"
KEY_MAP="/etc/nginx/conf.d/00-relay-key.conf"
SITE="/etc/nginx/sites-available/relay"
CACHE_DIR="/var/cache/nginx/adsblol"

log() { printf '\033[1;36m[relay]\033[0m %s\n' "$*"; }
die() { printf '\033[1;31m[relay] ERROR:\033[0m %s\n' "$*" >&2; exit 1; }

[ "$(id -u)" -eq 0 ] || die "run as root (sudo)"

# ---- preflight: required files must already be in place ---------------------
for f in "$CERT" "$KEY" "$RELAY_KEY_FILE"; do
  [ -s "$f" ] || die "missing $f -- scp it to the box first (see relay/README.md)"
done
chmod 600 "$KEY" "$RELAY_KEY_FILE"; chmod 644 "$CERT"

# ---- packages ---------------------------------------------------------------
log "installing nginx + unattended-upgrades"
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y -qq nginx ufw unattended-upgrades curl >/dev/null

# unattended security upgrades (idempotent: overwrite the toggle file)
cat > /etc/apt/apt.conf.d/20auto-upgrades <<'EOF'
APT::Periodic::Update-Package-Lists "1";
APT::Periodic::Unattended-Upgrade "1";
EOF

# ---- X-Relay-Key map (generated from the root-only key file) ----------------
# nginx reads config as root at load, so the map (which contains the key) is
# root-only. Regenerated each run so rotating relay.key + re-running is enough.
log "generating X-Relay-Key gate from $RELAY_KEY_FILE"
RELAY_KEY_VALUE="$(tr -d ' \t\r\n' < "$RELAY_KEY_FILE")"
[ -n "$RELAY_KEY_VALUE" ] || die "$RELAY_KEY_FILE is empty"
umask 077
cat > "$KEY_MAP" <<EOF
# GENERATED by setup-relay.sh from $RELAY_KEY_FILE -- do not edit. Root-only.
map \$http_x_relay_key \$relay_ok {
    default 0;
    "$RELAY_KEY_VALUE" 1;
}
EOF
umask 022
unset RELAY_KEY_VALUE

# ---- cache dir --------------------------------------------------------------
mkdir -p "$CACHE_DIR"; chown www-data:www-data "$CACHE_DIR"

# ---- relay vhost ------------------------------------------------------------
# Quoted heredoc: nginx $variables must survive to the file, not be expanded by
# bash. CACHE_TTL is substituted afterward via the __CACHE_TTL__ placeholder.
log "writing relay vhost (TTL=$CACHE_TTL)"
cat > "$SITE" <<'NGINX'
proxy_cache_path /var/cache/nginx/adsblol levels=1:2 keys_zone=adsblol:10m
                 max_size=100m inactive=10m use_temp_path=off;

# Log adsb.lol's OWN status (ustatus) + our cache status, so the soak measures the
# one honest unknown -- the real per-IP 429 rate -- from these logs:
#   grep -c 'ustatus=429' /var/log/nginx/relay.log
log_format relay '$time_iso8601 cache=$upstream_cache_status status=$status '
                 'ustatus=$upstream_status rt=$request_time uri="$request_uri"';

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;
    server_name _;

    ssl_certificate     /etc/ssl/cloudflare/origin.pem;
    ssl_certificate_key /etc/ssl/cloudflare/origin.key;
    ssl_protocols TLSv1.2 TLSv1.3;

    access_log /var/log/nginx/relay.log relay;

    # Unauthenticated liveness probe (no key, not logged).
    location = /healthz {
        access_log off;
        add_header Content-Type text/plain;
        return 200 "ok\n";
    }

    # Re-resolve api.adsb.lol periodically (its IP can move).
    resolver 1.1.1.1 8.8.8.8 valid=300s ipv6=off;

    location / {
        if ($relay_ok = 0) { return 403; }

        set $upstream "api.adsb.lol";
        proxy_pass https://$upstream;
        proxy_ssl_server_name on;
        proxy_ssl_name api.adsb.lol;
        proxy_set_header Host api.adsb.lol;
        proxy_set_header User-Agent "blipscope-relay";
        proxy_set_header X-Relay-Key "";   # never forward our secret upstream

        proxy_cache adsblol;
        proxy_cache_key "$request_uri";     # the Worker already quantizes tiles
        proxy_cache_valid 200 __CACHE_TTL__;
        proxy_cache_valid 429 500 502 503 504 1s;

        # Collapse concurrent identical polls (many CF colos, same tile) into ONE
        # upstream fetch -- this is what caps our adsb.lol request rate.
        proxy_cache_lock on;
        proxy_cache_lock_timeout 6s;

        # Absorb adsb.lol flakiness here, not in the fleet: serve last-good while
        # refreshing, or if adsb.lol errors/times out/429s.
        proxy_cache_use_stale updating error timeout
                              http_429 http_500 http_502 http_503 http_504;
        proxy_cache_background_update on;

        add_header X-Relay-Cache $upstream_cache_status always;
        proxy_connect_timeout 5s;
        proxy_read_timeout 8s;
    }
}
NGINX
sed -i "s/__CACHE_TTL__/$CACHE_TTL/" "$SITE"

ln -sf "$SITE" /etc/nginx/sites-enabled/relay
rm -f /etc/nginx/sites-enabled/default

# ---- firewall ---------------------------------------------------------------
# Allow SSH BEFORE enabling ufw so we can't lock ourselves out.
log "configuring ufw (22 + 443-from-Cloudflare)"
ufw allow 22/tcp >/dev/null
ufw --force enable >/dev/null
# Only Cloudflare may reach 443 (the relay is orange-clouded; direct hits are
# refused at L3, the X-Relay-Key gate is the L7 backstop).
for url in https://www.cloudflare.com/ips-v4 https://www.cloudflare.com/ips-v6; do
  while read -r range; do
    [ -n "$range" ] && ufw allow from "$range" to any port 443 proto tcp >/dev/null || true
  done < <(curl -fsS "$url" || true)
done

# ---- validate + reload ------------------------------------------------------
log "nginx -t"
nginx -t
systemctl reload nginx
systemctl enable nginx >/dev/null 2>&1 || true

log "done. verify:"
log "  curl -s -o /dev/null -w '%{http_code}\\n' https://localhost/healthz --resolve localhost:443:127.0.0.1 -k   # 200"
log "  curl -s -o /dev/null -w '%{http_code}\\n' https://localhost/v2/lat/40/lon/-74/dist/50 --resolve localhost:443:127.0.0.1 -k   # 403 (no key)"
