#!/usr/bin/env bash
#
# Blipscope egress relay -- idempotent root setup for one box (Debian/Ubuntu).
# Safe to re-run; converges the box to the desired state each time.
#
# WHAT IT DOES
#   - installs nginx (apt) + unattended-upgrades
#   - writes the caching relay vhost: proxy_cache + cache_lock, use_stale on
#     error/timeout/429, TTL a clearly-marked tunable (CACHE_TTL, starts 6s)
#   - X-Relay-Key gate: 403 unless the caller presents the key, read from a
#     ROOT-ONLY file (never in this script or in git)
#   - installs the Cloudflare Origin certificate for TLS (443)
#   - ufw: allow 22 + 443-from-Cloudflare-ranges only, deny the rest
#   - unauthenticated /healthz
#   - adds X-Relay-Cache: HIT|MISS|STALE|UPDATING and logs upstream_status so the
#     soak can read adsb.lol's REAL per-IP 429 behaviour from the relay's own logs
#
# PREREQUISITES -- scp these to the box first (see relay/README.md):
#   /etc/ssl/cloudflare/origin.pem   Cloudflare Origin cert   (0644 root:root)
#   /etc/ssl/cloudflare/origin.key   its private key          (0600 root:root)
#   /etc/nginx/relay.key             the X-Relay-Key value     (0600 root:root)
#
# RUN:  sudo CACHE_TTL=6s bash setup-relay.sh
set -euo pipefail

# ---- tunables ---------------------------------------------------------------
# THE scaling knob. adsb.lol upstream fetch rate ~= (distinct hot tiles) / CACHE_TTL,
# independent of device count (the fleet collapses to one fetch per tile per TTL).
# 8s: the device flags "stale" past staleFactor(3) x poll interval = 15s on an ACTIVE
# (5s) poll, so the data it receives must stay well under 15s old. TTL is the floor on
# how fresh a tile can be; 8s keeps a rural tile (small body, ~4s foreground fetch)
# refreshing fast enough that the device sees ~10-15s-old data. It is NOT a pile-up
# risk: refresh is foreground + proxy_cache_lock, so a busy tile whose fetch (~16s)
# exceeds the TTL just refreshes at its fetch rate (one at a time) while use_stale
# serves the rest -- the TTL is a floor, the throttle is the real ceiling. Lower for
# freshness; raise only if a soak shows adsb.lol 429ing at our fetch rate.
CACHE_TTL="${CACHE_TTL:-8s}"

UPSTREAM_HOST="api.adsb.lol"
CERT="/etc/ssl/cloudflare/origin.pem"
KEY="/etc/ssl/cloudflare/origin.key"
RELAY_KEY_FILE="/etc/nginx/relay.key"
KEY_MAP="/etc/nginx/conf.d/00-relay-key.conf"
SITE="/etc/nginx/sites-available/relay"
CACHE_DIR="/var/cache/nginx/adsblol"

log() { printf '\033[1;36m[relay]\033[0m %s\n' "$*"; }
die() { printf '\033[1;31m[relay] ERROR:\033[0m %s\n' "$*" >&2; exit 1; }

[ "$(id -u)" -eq 0 ] || die "run as root (sudo)"

# ---- preflight: required files must already be in place ---------------------
for f in "$CERT" "$KEY" "$RELAY_KEY_FILE"; do
  [ -s "$f" ] || die "missing $f -- scp it to the box first (see relay/README.md)"
done
chmod 600 "$KEY" "$RELAY_KEY_FILE"; chmod 644 "$CERT"

# ---- packages ---------------------------------------------------------------
log "installing nginx + unattended-upgrades"
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y -qq nginx ufw unattended-upgrades curl >/dev/null

# unattended security upgrades (idempotent: overwrite the toggle file)
cat > /etc/apt/apt.conf.d/20auto-upgrades <<'EOF'
APT::Periodic::Update-Package-Lists "1";
APT::Periodic::Unattended-Upgrade "1";
EOF

# ---- X-Relay-Key map (generated from the root-only key file) ----------------
# nginx reads config as root at load, so the map (which contains the key) is
# root-only. Regenerated each run so rotating relay.key + re-running is enough.
log "generating X-Relay-Key gate from $RELAY_KEY_FILE"
RELAY_KEY_VALUE="$(tr -d ' \t\r\n' < "$RELAY_KEY_FILE")"
[ -n "$RELAY_KEY_VALUE" ] || die "$RELAY_KEY_FILE is empty"
umask 077
cat > "$KEY_MAP" <<EOF
# GENERATED by setup-relay.sh from $RELAY_KEY_FILE -- do not edit. Root-only.
# The 64-char relay key exceeds nginx's default map_hash_bucket_size (64 on many
# builds), which fails "could not build map_hash" at load -- bump it.
map_hash_bucket_size 128;
map \$http_x_relay_key \$relay_ok {
    default 0;
    "$RELAY_KEY_VALUE" 1;
}
EOF
umask 022
unset RELAY_KEY_VALUE

# ---- cache dir --------------------------------------------------------------
mkdir -p "$CACHE_DIR"; chown www-data:www-data "$CACHE_DIR"

# ---- shared upstream proxy directives (included by each location) -----------
# Factored out so the two locations below differ ONLY in cache TTL. Quoted
# heredoc: nginx $variables must reach the file, not be expanded by bash.
mkdir -p /etc/nginx/snippets
cat > /etc/nginx/snippets/relay-upstream.conf <<'NGINX'
if ($relay_ok = 0) { return 403; }
set $upstream "api.adsb.lol";
proxy_pass https://$upstream;
proxy_ssl_server_name on;
proxy_ssl_name api.adsb.lol;
proxy_set_header Host api.adsb.lol;
proxy_set_header User-Agent "blipscope-relay";
proxy_set_header X-Relay-Key "";   # never forward our secret upstream
proxy_cache adsblol;
proxy_cache_key "$request_uri";     # the Worker already quantizes tiles
# OUR proxy_cache_valid (per location) governs the cache, not adsb.lol's headers.
proxy_ignore_headers Cache-Control Expires Set-Cookie;
# Collapse concurrent identical requests into ONE upstream fetch.
proxy_cache_lock on;
proxy_cache_lock_timeout 6s;
# Absorb adsb.lol slowness here: serve last-good instantly while a refresh runs.
# ONLY 200s are cached (per location) -- a 429 is never cached, it falls through
# to this use_stale, which serves the last good response.
#
# adsb.lol bandwidth-throttles the ANONYMOUS API to ~100 kbit/s (~12 KB/s), measured
# identically from both relays AND an unrelated home ISP -- a server-side egress cap,
# not a per-IP limit we can escape. A busy 160 km tile is ~187 KB => a full fetch
# takes ~16 s (rural tiles are ~1 KB => instant). The relay makes that invisible by
# COLLAPSING the fleet to one upstream fetch per tile per TTL and serving stale in the
# meantime -- but the refresh runs in the FOREGROUND, NOT via background_update.
#
# background_update ORPHANS the refresh under sparse polling: nginx serves the stale
# copy instantly, the triggering client disconnects, and the in-flight update subrequest
# is cut short before it caches. A tile polled every ~15 s then re-serves stale and
# re-orphans forever (observed: a tile stuck 21 min stale while the device polled it
# every 15 s; only a 5 s curl loop kept a refresh alive long enough to land). Foreground
# has no orphan: the request that finds the tile stale DOES the fetch and waits for it,
# so fresh data always lands. use_stale `updating` serves any CONCURRENT requests stale
# while that one fetch runs, so only the single refreshing request waits. And the wait is
# invisible: the Worker's revalidation runs in ctx.waitUntil (the device already has its
# instant answer from the Worker cache), so the relay can take 4-16 s to return fresh.
#
# The earlier "stuck in UPDATING" wedge was proxy_read_timeout (15 s) landing ~0.1 s
# SHORT of the 15.7 s throttled body, so a refresh timed out before caching and re-fired
# forever. read_timeout is now 30 s (below) so the throttled body completes. Keep the
# requested radius bounded (Worker R_BUCKETS_KM) so no single fetch approaches 30 s.
proxy_cache_use_stale updating error timeout http_429 http_500 http_502 http_503 http_504;
add_header X-Relay-Cache $upstream_cache_status always;
# Orange-clouded: tell the CF edge NOT to add its own cache (Worker ignores this).
add_header Cache-Control "no-store" always;
proxy_connect_timeout 5s;
proxy_read_timeout 30s;   # anon throttle ~12 KB/s; a 187 KB busy tile is ~16s. Must
                          # exceed the worst throttled body or bg refresh never caches.
NGINX

# ---- relay vhost ------------------------------------------------------------
log "writing relay vhost (tile TTL=$CACHE_TTL, hex TTL=1h)"
cat > "$SITE" <<'NGINX'
proxy_cache_path /var/cache/nginx/adsblol levels=1:2 keys_zone=adsblol:10m
                 max_size=100m inactive=2h use_temp_path=off;

# Log adsb.lol's OWN status (ustatus) + our cache status, so the soak measures the
# one honest unknown -- the real per-IP 429 rate -- from these logs:
#   grep -c 'ustatus=429' /var/log/nginx/relay.log
log_format relay '$time_iso8601 cache=$upstream_cache_status status=$status '
                 'ustatus=$upstream_status rt=$request_time uri="$request_uri"';

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    # (no HTTP/2: not needed for a machine-to-machine proxy, and the standalone
    # `http2 on;` directive only exists in nginx >= 1.25.1; Ubuntu 24.04 ships 1.24.)
    server_name _;

    ssl_certificate     /etc/ssl/cloudflare/origin.pem;
    ssl_certificate_key /etc/ssl/cloudflare/origin.key;
    ssl_protocols TLSv1.2 TLSv1.3;

    access_log /var/log/nginx/relay.log relay;

    # Unauthenticated liveness probe (no key, not logged).
    location = /healthz {
        access_log off;
        add_header Content-Type text/plain;
        return 200 "ok\n";
    }

    # Re-resolve api.adsb.lol periodically (its IP can move).
    resolver 1.1.1.1 8.8.8.8 valid=300s ipv6=off;

    # Aircraft METADATA (/v2/hex) is static -- type/reg don't change -- and an
    # enrichment sweep asks for many distinct hexes at once. Cache it LONG so each
    # hex hits adsb.lol at most ~once/hour instead of every tile TTL. This is what
    # stops the /v2/hex 429 storm that was also starving tile revalidation.
    location ^~ /v2/hex/ {
        include /etc/nginx/snippets/relay-upstream.conf;
        proxy_cache_valid 200 1h;
    }

    # Live POSITIONS (/v2/lat), routeset, everything else: short TTL for a fresh
    # picture. 200s only; a 429 falls through to use_stale (last good tile).
    location / {
        include /etc/nginx/snippets/relay-upstream.conf;
        proxy_cache_valid 200 __CACHE_TTL__;
    }
}
NGINX
sed -i "s/__CACHE_TTL__/$CACHE_TTL/" "$SITE"

ln -sf "$SITE" /etc/nginx/sites-enabled/relay
rm -f /etc/nginx/sites-enabled/default

# NB: an earlier "tile warmer" systemd service (blipscope-warm) was tried here and
# REMOVED 2026-07-22. It re-requested hot tiles every 3 s to keep them warm, but on a
# stale tile that adsb.lol was 429ing it retried every 3 s (429s aren't cached), which
# turned a transient 429 into a self-sustaining storm (~58% of upstream contacts 429).
# It was also redundant: foreground refresh already serves age~0 under sparse client
# polling, because the requesting client waits for the fetch. Do NOT reintroduce a
# warmer without an upstream rate limit / 429 backoff. If a box still has it, this run
# leaves it stopped; remove with: systemctl disable --now blipscope-warm.

# ---- firewall ---------------------------------------------------------------
# Allow SSH BEFORE enabling ufw so we can't lock ourselves out.
log "configuring ufw (22 + 443-from-Cloudflare)"
ufw allow 22/tcp >/dev/null
ufw --force enable >/dev/null
# Only Cloudflare may reach 443 (the relay is orange-clouded; direct hits are
# refused at L3, the X-Relay-Key gate is the L7 backstop).
for url in https://www.cloudflare.com/ips-v4 https://www.cloudflare.com/ips-v6; do
  while read -r range; do
    [ -n "$range" ] && ufw allow from "$range" to any port 443 proto tcp >/dev/null || true
  done < <(curl -fsS "$url" || true)
done

# ---- validate + reload ------------------------------------------------------
log "nginx -t"
nginx -t
systemctl reload nginx
# Belt-and-suspenders: ensure the removed warmer stays gone on re-run.
systemctl disable --now blipscope-warm >/dev/null 2>&1 || true
systemctl enable nginx >/dev/null 2>&1 || true

log "done. verify:"
log "  curl -s -o /dev/null -w '%{http_code}\\n' https://localhost/healthz --resolve localhost:443:127.0.0.1 -k   # 200"
log "  curl -s -o /dev/null -w '%{http_code}\\n' https://localhost/v2/lat/40/lon/-74/dist/50 --resolve localhost:443:127.0.0.1 -k   # 403 (no key)"
