#!/usr/bin/env node
// The locate helper's formatter output, written to a fixture the FIRMWARE's parser is graded on.
//
// The helper (src/locatepage.ts) formats the position; the device's settings page writes it
// into the boxes and the device parses it on Save with include/CoordParse.h. Those are two
// languages on two sides of a postMessage, so the host test takes its input from THIS side:
// test/host/test_locate_format.cpp reads test/fixtures/locate-format.txt and requires every
// line to parse, and to land within 0.00005 of the source position.
//
// Each line: "<formatted pair>|<source lat>|<source lon>". The positions cover both hemispheres,
// the +-90/+-180 bounds, values that round across .99995, and -0.00004 (which must come out as
// 0.0000, never -0.0000).
//
// RUN:  node scripts/locate-fixture.mjs           regenerate
//       node scripts/locate-fixture.mjs --check   fail (exit 1) if the checked-in file is stale

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { build } from "esbuild";

const OUT = "../test/fixtures/locate-format.txt";
const POSITIONS = [
  [44.05824, -121.31534], [-33.8688197, 151.2092955], [51.5007292, -0.1246254],
  [-0.00004, 0.00004], [90, 180], [-90, -180], [45.99995, -122.99995], [0.99995, -0.99995],
  [11.1111111, -22.2222222], [-89.99996, 179.99996],
];

const out = await build({ entryPoints: ["src/locatepage.ts"], bundle: true, format: "esm", platform: "neutral", write: false, logLevel: "silent" });
const mod = await import("data:text/javascript;base64," + Buffer.from(out.outputFiles[0].text).toString("base64"));

const body = "# Generated by proxy/scripts/locate-fixture.mjs from src/locatepage.ts formatCoord. Do not edit.\n" +
  POSITIONS.map(([la, lo]) => `${mod.formatCoord(la)}, ${mod.formatCoord(lo)}|${la}|${lo}`).join("\n") + "\n";

if (process.argv.includes("--check")) {
  const cur = existsSync(OUT) ? readFileSync(OUT, "utf8").replace(/\r\n/g, "\n") : "";
  if (cur !== body) { console.error(`${OUT} is stale. Run: node scripts/locate-fixture.mjs`); process.exit(1); }
  console.log(`ok: ${OUT} matches formatCoord (${POSITIONS.length} positions)`);
} else {
  writeFileSync(OUT, body);
  console.log(`wrote ${OUT} (${POSITIONS.length} positions)`);
}
